import Foundation
import CryptoKit
import CommonCrypto

// MARK: - BIP-39 Core
// Implements the BIP-39 standard for mnemonic generation and seed derivation.
// Reference: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
//
// Security model:
// - Entropy is generated by the OS CSRNG (SecRandomCopyBytes). No fallback.
// - PBKDF2-HMAC-SHA512 with 2048 rounds derives a 64-byte master seed.
// - The mnemonic is NEVER stored; only the derived seed reaches Keychain.

enum BIP39Error: LocalizedError {
    case rngFailure
    case invalidWordCount
    case unknownWord(String)
    case checksumMismatch
    case encodingFailure

    var errorDescription: String? {
        switch self {
        case .rngFailure: return "OS random number generator unavailable."
        case .invalidWordCount: return "Mnemonic must be 12 or 24 words."
        case .unknownWord(let w): return "'\(w)' is not in the BIP-39 wordlist."
        case .checksumMismatch: return "Mnemonic checksum invalid — one or more words may be wrong."
        case .encodingFailure: return "Could not encode mnemonic to UTF-8."
        }
    }
}

enum BIP39 {

    // MARK: - Generation

    /// Generates a 12-word mnemonic from 128 bits of cryptographic entropy.
    static func generateMnemonic(wordCount: Int = 12) throws -> [String] {
        let entropyBytes: Int
        switch wordCount {
        case 12: entropyBytes = 16  // 128 bits
        case 24: entropyBytes = 32  // 256 bits
        default: throw BIP39Error.invalidWordCount
        }

        var entropy = [UInt8](repeating: 0, count: entropyBytes)
        let status = SecRandomCopyBytes(kSecRandomDefault, entropy.count, &entropy)
        guard status == errSecSuccess else { throw BIP39Error.rngFailure }

        return try mnemonicWords(from: Data(entropy))
    }

    // MARK: - Seed Derivation

    /// Derives a 64-byte master seed from a mnemonic phrase using PBKDF2-HMAC-SHA512.
    /// The passphrase adds an optional second factor. It is empty by default per standard.
    static func deriveSeed(from mnemonic: [String], passphrase: String = "") throws -> Data {
        let mnemonicStr = mnemonic.joined(separator: " ")
        guard let mnemonicData = mnemonicStr.data(using: .utf8),
              let saltData = ("mnemonic" + passphrase).data(using: .utf8) else {
            throw BIP39Error.encodingFailure
        }

        var derivedKey = [UInt8](repeating: 0, count: 64)
        let result = mnemonicData.withUnsafeBytes { mnemonicPtr in
            saltData.withUnsafeBytes { saltPtr in
                CCKeyDerivationPBKDF(
                    CCPBKDFAlgorithm(kCCPBKDF2),
                    mnemonicPtr.baseAddress?.assumingMemoryBound(to: Int8.self),
                    mnemonicData.count,
                    saltPtr.baseAddress?.assumingMemoryBound(to: UInt8.self),
                    saltData.count,
                    CCPseudoRandomAlgorithm(kCCPRFHmacAlgSHA512),
                    2048,
                    &derivedKey,
                    64
                )
            }
        }
        guard result == kCCSuccess else { throw BIP39Error.encodingFailure }
        return Data(derivedKey)
    }

    // MARK: - Validation

    /// Validates a mnemonic phrase string and returns the individual words.
    static func validate(_ phrase: String) throws -> [String] {
        let words = phrase
            .lowercased()
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }

        guard words.count == 12 || words.count == 24 else {
            throw BIP39Error.invalidWordCount
        }

        let wordlistSet = Set(BIP39Wordlist.english)
        for word in words {
            guard wordlistSet.contains(word) else { throw BIP39Error.unknownWord(word) }
        }

        // Reconstruct entropy and verify checksum
        let indices = try words.map { word -> Int in
            guard let idx = BIP39Wordlist.english.firstIndex(of: word) else {
                throw BIP39Error.unknownWord(word)
            }
            return idx
        }

        // Pack indices back to bits and verify checksum
        let totalBits = words.count * 11
        let checksumBits = totalBits / 33
        let entropyBits = totalBits - checksumBits
        var bits = [UInt8](repeating: 0, count: totalBits)

        for (i, idx) in indices.enumerated() {
            for b in 0..<11 {
                bits[i * 11 + b] = UInt8((idx >> (10 - b)) & 1)
            }
        }

        let entropyByteCount = entropyBits / 8
        var entropy = [UInt8](repeating: 0, count: entropyByteCount)
        for i in 0..<entropyBits {
            entropy[i / 8] |= bits[i] << (7 - (i % 8))
        }

        let hash = SHA256.hash(data: Data(entropy))
        let hashByte = hash.first ?? 0
        let expectedChecksum = hashByte >> (8 - checksumBits)
        var actualChecksum: UInt8 = 0
        for i in 0..<checksumBits {
            actualChecksum |= bits[entropyBits + i] << (checksumBits - 1 - i)
        }

        guard actualChecksum == expectedChecksum else { throw BIP39Error.checksumMismatch }
        return words
    }

    // MARK: - Private Helpers

    private static func mnemonicWords(from entropy: Data) throws -> [String] {
        let hashByte = SHA256.hash(data: entropy).first ?? 0
        let checksumBits = entropy.count * 8 / 32

        var bits = [UInt8]()
        for byte in entropy {
            for b in (0..<8).reversed() { bits.append((byte >> b) & 1) }
        }
        // Append checksum bits
        for b in (8 - checksumBits..<8).reversed() {
            bits.append((hashByte >> b) & 1)
        }

        var words = [String]()
        let wordlist = BIP39Wordlist.english
        for i in stride(from: 0, to: bits.count, by: 11) {
            var idx = 0
            for b in 0..<11 { idx = (idx << 1) | Int(bits[i + b]) }
            words.append(wordlist[idx])
        }
        return words
    }
}
