pub mod types;

use std::ffi::{CStr, CString};
use std::os::raw::c_char;

use types::{Note, Nullifier, TransferPayload, FFIResult};

/// Mocks generating a Starknet Proof for a Private Transfer
/// # Safety
/// This function is meant to be called from FFI. The caller must ensure that the pointer
/// passed is a valid null-terminated C string. The caller is also responsible for freeing
/// the returned string using `free_rust_string`.
#[no_mangle]
pub unsafe extern "C" fn generate_transfer_proof(
    notes_json: *const c_char,
) -> *mut c_char {
    if notes_json.is_null() {
        let err = FFIResult::Error("Received null pointer".to_string());
        let json_err = serde_json::to_string(&err).unwrap();
        return CString::new(json_err).unwrap().into_raw();
    }

    let c_str = CStr::from_ptr(notes_json);
    let str_slice = match c_str.to_str() {
        Ok(s) => s,
        Err(_) => {
            let err = FFIResult::Error("Invalid UTF-8 sequence".to_string());
            let json_err = serde_json::to_string(&err).unwrap();
            return CString::new(json_err).unwrap().into_raw();
        }
    };

    // Simulate parsing the input wrapper (e.g. array of Notes)
    let _notes: Vec<Note> = match serde_json::from_str(str_slice) {
        Ok(n) => n,
        Err(e) => {
            let err = FFIResult::Error(format!("Failed to parse notes: {}", e));
            let json_err = serde_json::to_string(&err).unwrap();
            return CString::new(json_err).unwrap().into_raw();
        }
    };

    // MOCK: Generate fake proof, nullifiers, and commitments
    let mock_payload = TransferPayload {
        proof: vec!["0x123...mock_proof".to_string(), "0x456...mock_proof".to_string()],
        nullifiers: vec!["0xabc...nullifier".to_string()],
        new_commitments: vec!["0xdef...commitment".to_string()],
        fee: "100000000000000".to_string(), // 0.0001 ETH
    };

    let result = FFIResult::Success(serde_json::to_string(&mock_payload).unwrap());
    
    match serde_json::to_string(&result) {
        Ok(json_str) => CString::new(json_str).unwrap().into_raw(),
        Err(_) => CString::new("{\"Error\":\"Serialization failed\"}").unwrap().into_raw()
    }
}

/// Frees a string allocated by Rust crossing the FFI boundary
/// # Safety
/// Caller must ensure pointer string was generated by Rust via CString::into_raw.
#[no_mangle]
pub unsafe extern "C" fn free_rust_string(s: *mut c_char) {
    if s.is_null() {
        return;
    }
    let _ = CString::from_raw(s); // takes ownership and drops it
}
